### ISSUE TITLE
Error when the context is greater than 2047 characters.

### ISSUE THREAD

**Issue by hrisheekeshr** [surbhardwaj/BERT-for-Question-Answering#3]
`IndexError                                
Traceback (most recent call last)
~/bert/BERT-QnA-Squad_2.0_Finetuned_Model/Code/Test_Batch.py in <module>()
    632 
    633 if __name__ == "__main__":
--> 634     main()

~/bert/BERT-QnA-Squad_2.0_Finetuned_Model/Code/Test_Batch.py in main()
    590                 end_logits =   batch_end_logits[i].detach().cpu().tolist()
    591                 feature = eval_features[example_index.item()]
--> 592                 examp = examples[example_index.item()]
    593                 unique_id = int(feature.unique_id)
    594                 features.append(feature)

IndexError: list index out of range
`

**Comment by surbhardwaj** [comment]
Could you please share the paragraph and question you were testing on. 
Thanks...

**Comment by hrisheekeshr** [comment]
[input_file.txt](https://github.com/surbhardwaj/BERT-QnA-Squad_2.0_Finetuned_Model/files/3016371/input_file.txt)

**Comment by surbhardwaj** [comment]
I had fixed the bug. Hope it resolves your issue.

**Comment by hrisheekeshr** [comment]
Thanks
